package exceptions

import "errors"

var ErrUnexpected = errors.New("unexpected error occurred")
